#ifndef CONSTANTS_H
#define CONSTANTS_H

#define BUFFER_SIZE 128
#define SAMPLE_RATE 48000
#define MAGIC_LEVEL_COEFF 100.0
#define SECOND_PER_SAMPLE 0.000020833
#define LEVEL_METER_RMS_SAMPLE_COUNT 60
#define LEVEL_METER_AVERAGE_CYCLE_COUNT 15
#define COMPRESSOR_UPDATE_SAMPLE_COUNT 60

#define MIDI_PUSHED_FACTOR 6

#define UI_FRAMERATE 30
#define UI_OUTMETER_HEIGHT 60
#define UI_SHAFT_WIDTH 8
#define UI_LEVEL_MAGIC_COEFF 0.0045

#endif // CONSTANTS_H

